# Generated by Django 3.2.4 on 2021-06-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210616_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, upload_to='file/', verbose_name='简历附件'),
        ),
        migrations.AddField(
            model_name='resume',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='个人照片'),
        ),
    ]
